### ISSUE TITLE
Bug:Issue with π button

### ISSUE THREAD

**Issue by r6654kumar** [Ctoic/CalHub#61]
When you click Any Number *(or any other operator) π answer is always π but when you click π *(or any other operator) it works fine.

**Comment by Ctoic** [comment]
Will you like to work on this issue ?

**Comment by r6654kumar** [comment]
Thank you for assigning me...Will work on it soon.

**Comment by Ctoic** [comment]
Looking forward for your contributions.  Best of luck and don't forget to star the repo 😇

**Comment by r6654kumar** [comment]
Done with Pull Request " Fixed Bug in Pi calculations"
